version: '3.8'

services:
  webapp:
    build: ./webapp
    container_name: devsecops-webapp
    ports:
      - "3000:3000"
    networks:
      - monitoring_default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  monitoring_default:
    driver: bridge